# Project information
site_name: Jurnal Korea
site_url: https://reimuchsan.github.io/jurnalkorwareng/
site_description: >-
  Materi atau catatan acak tentang Korea

# Copyright
copyright: "Copyright &copy; 2026 reimuchsan"

# Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: lucide/sun-moon
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: lucide/sun
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: teal
      toggle:
        icon: lucide/moon-star
        name: Switch to system preference
  favicon: assets/favicon/favicon.png
  icon:
    tag:
      default: lucide/hash
    logo: material/ideogram-cjk-variant

extra_css:
  - assets/stylesheets/extra.css

# Plugins
plugins:
  - search
  - tags

# Additional configuration
extra:
  annotate:
    json: [.s2]
  status:
    new: Recently added
    deprecated: Deprecated
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/reimuchsan
  tags:
    default: default

# Extensions


# Page tree
nav:
- Home: "index.md"
- WARENG'ESO:
    - "WARENG-ESO/index.md"
    - Dasar:
        - "WARENG-ESO/Dasar/Huruf.md"
        - "WARENG-ESO/Dasar/Angka.md"
        - "WARENG-ESO/Dasar/Tata Bahasa.md"
    - Lembar FC:
        - "WARENG-ESO/Lembar FC/Keterangan Tempat = 장소.md"
        - "WARENG-ESO/Lembar FC/Warna = 색깔.md"
        - "WARENG-ESO/Lembar FC/Keterangan Frekuensi.md"
        - "WARENG-ESO/Lembar FC/Lawan Kata = 반데단어.md"
        - "WARENG-ESO/Lembar FC/수량사 = Kata Satuan.md"
        - "WARENG-ESO/Lembar FC/서류 와 카드 = Dokumen dan Kartu.md"
        - "WARENG-ESO/Lembar FC/동사 = Kata Kerja.md"
        - "WARENG-ESO/Lembar FC/Kata Kerja = 동사.md"
        - "WARENG-ESO/Lembar FC/Latihan Kata = 단어 연습.md"
        - "WARENG-ESO/Lembar FC/Penyakit = 병.md"
        - "WARENG-ESO/Lembar FC/Perhitungan Hari.md"
        - "WARENG-ESO/Lembar FC/Keluarga = 가족.md"
        - "WARENG-ESO/Lembar FC/인사말 = Ungkapan Salam.md"
        - "WARENG-ESO/Lembar FC/명사 = Kata Benda.md"
        - "WARENG-ESO/Lembar FC/Buah = 과일.md"
        - "WARENG-ESO/Lembar FC/명칭 = Anggota Tubuh.md"
        - "WARENG-ESO/Lembar FC/Waktu = 시간.md"
        - "WARENG-ESO/Lembar FC/Cuaca = 날씨.md"
        - "WARENG-ESO/Lembar FC/Sayuran = 야체 - 체소료.md"
- Guide:
    - "Guide/index.md"
    - Aplikasi:
        - "Guide/Aplikasi/index.md"
